/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:05a1f4f1-9dda-47d9-90ae-07f8c1497331",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_MYxcaED60",
    "aws_user_pools_web_client_id": "57r9inuc7r8gngj4k8kjtde1t0",
    "oauth": {}
};


export default awsmobile;
